[package]
name = "kcovreader"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
byteorder = "1.4.3"
addr2line = "0.17.0"
memmap2 = "0.5.0"
object = "0.27.1"
shared_memory = "0.12.0"
log = "0.4.17"